### ISSUE TITLE
document failure/retry modes in distributed use

### ISSUE THREAD

**Issue by heavenlyhash** [chrislusf/glow#61]
Glow looks really elegant and simple to get started with and cool!

As a new potential user, my biggest question is how error handling and re-try (if any) works in distributed mode.  Specifically, I was hoping to find either "at most once" or "at least once" delivery referenced in the documentation.  (I've browsed the wiki, readme, and skimmed some of the godoc so far -- I might've missed it, but if so, consider this a request for a more central link to the info :) )

I'm not sure if the "at-[most|least]-once" delivery terminology is universal, but here's a description if I'm speaking gobbygook: http://bravenewgeek.com/you-cannot-have-exactly-once-delivery/

Based on the functional intentions of glow, I'm *guessing* it's at-least-once delivery semantics, but I'd really like to know for sure -- it's important in case I want to call other functions that may have side effects (such functions would have to be carefully designed to be idempotent, obviously).

**Comment by chrislusf** [comment]
Good point. I feel "at most once" or "at least once" sounds very professional when I hear someone else using these terms, because I always have to pause a bit to think about what it really means. I think glow can be classified to "at most once", for now.

Actually glow does not try to use these terms. Glow runs just like a common program. It does not try to auto-recover from any actual machine shutdown. It just breaks like having an exception.

So this in a sense just give back the retry decision to the user. The user can decide to run it again, or fix some real issue with the code. This would not work for google/facebook scale clusters, but should work fine for 10 ~ 20 nodes.

You are welcome to adjust the readme in a better way to explain this.
